### ISSUE TITLE
BUG-METHOD_UNIT name picking up Incorrectly

### ISSUE THREAD

**Issue by charangirijala** [charangirijala/apex-log-analyzer#19]
**Describe the bug**
Method Unit name not properly picked up while parsing

**To Reproduce**
Sample Log:
[externallogfil.log](https://github.com/user-attachments/files/17706254/externallogfil.log)

**Expected behavior**
Pick up correct methodUnit Name while processing the line

**Screenshots**
<img width="704" alt="image" src="https://github.com/user-attachments/assets/a129ed3a-fa94-437c-9151-d584f2a6a52c">

**Additional context**

**Comment by Sreshtag** [comment]
Hi @charangirijala 
Please check if below line of code better suits this scenario to extraxct method name

**To Reproduce**
Steps to reproduce the behavior:
**Sample Log:**
[externallogfil.log](https://github.com/user-attachments/files/17707005/externallogfil.log)

Expected behavior
Picking up the right method unit name


![image](https://github.com/user-attachments/assets/5b928303-f61c-4968-8037-013abc8bf097)


**previously** we were splitting the line over '.'
**now** we are removing the substring within() and splitting then adding it back to the last element of the split.
